name: CI (Detekt and Assemble)

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: "detekt"
        uses: natiginfo/action-detekt-all@1.19.0

      - name: checkout@v2
        uses: actions/checkout@v2
        
      - name: Set Up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Build Project
        run: ./gradlew assemble
