name: new atempt CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set Up JDK 11             // 1
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Change wrapper permissions  // 2
        run: chmod +x ./gradlew

      - name: Build Project               // 4
        run: ./gradlew assemble
